const title = ["Mr.", "Mrs.", "Miss", "Dr.", "Dr. (Mrs)", "Prof."];
const expertise_fields = [
  "Programming",
  "Computer Hardware",
  "Database Management Systems",
  "Database Design",
  "Programming Languages",
  "Algorithms",
  "Data Structures",
  "Microprocessors",
  "Assembly Language Programming",
  "Digital Logic Design",
  "Computer Architecture",
  "Digital Systems Design",
  "Data Communication Protocols",
  "Computer Networks",
  "Data Structures and Algorithms",
  "Operating System Design and Implementation",
  "Operating Systems",
  "Formal Languages and Grammars",
  "Theoretical Foundations of Computing",
  "Practical application of Digital Systems Design concepts",
  "Discrete Mathematics",
  "Logic Design",
  "Optimization Techniques",
  "Applied Mathematics for Problem Solving",
  "Design and Analysis of Algorithms",
  "Advanced Network Protocols",
  "Structured Programming",
  "Numerical Analysis Techniques for Scientific Computing",
  "System Modeling and Simulation Techniques",
  "Industrial Automation",
  "Process Control Systems",
  "Software Project Management Techniques",
  "Game Design and Development Principles",
  "Programming Language Design and Theory",
  "Web Development Technologies and Frameworks",
  "Compiler Design and Construction",
  "Expert Systems",
  "Mobile Communications Networks",
  "Network Security",
  "Concurrent Programming",
  "Computer Animation",
  "Computer Graphics",
  "Advanced Database Design Techniques",
  "Database Administration",
  "Machine learning",
  "Artificial Intelligence",
  "Natural Language Processing",
  "Data Science",
  "Software Engineering",
  "Software Design Principles",
  "Advanced Software Development Methodologies",
];

const getOptions = (req, res) => {
  res.status(200).json({
    options: { title, expertise_fields },
  });
};

module.exports = { getOptions };
